language: node_js
node_js:
  - "0.10"
before_install:
  - rvm use 1.9.3
install:
  - travis_retry npm install -g grunt-cli
  - travis_retry npm install
  - travis_retry gem install "sass:~>3.3.5"
matrix:
  fast_finish: true
